[feat]
label = "Feat ğŸ¸"
description = "A new feature"
vars = ["title", "nn"]
title = "feat: ğŸ¸ {{title}}"
branch_pattern = "^feature/GP-{{nn}}$"
body = """
\\## Breaking changes

Closes [GP-{{nn}}](https://connectnodes.atlassian.net/browse/GP-{{nn}})
"""
